### Create Report
POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "Toyota",
    "model": "altis",
    "year": 2020,
    "mileage": 15000,
    "price": 20000,
    "lng": 0,
    "lat": 0
}

### Patch Report
PATCH http://localhost:3000/reports/1
Content-Type: application/json

{
    "approved": true
}


 
### get an estimate for existing vehicles
GET http://localhost:3000/reports?make=Toyota&model=altis&year=2020&price=20000&mileage=15000&lng=0&lat=0
 